name: sachin
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run my first python file
        run: |
          cd python
          python test.py
